---
# General UPS configuration
ups_configuration__upsd:
  upsmon: master
  actions: SET
  instcmds: ALL

ups_configuration__upsmon:
  minsupplies: 1
  shutdowncmd: /sbin/shutdown -h +0
  pollfreq: 5
  pollfreqalert: 5
  hostsync: 15
  deadtime: 15
  powerdownflag: /etc/killpower
  rbwarntime: 43200
  nocommwarntime: 300
  finaldelay: 5
  monitor:
    system: "{{ ups_configuration__ups.name }}@localhost"
    powervalue: 1
    type: master
