---
- name: Restart NUT services after configuration
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  become: true
  listen: restart_nut
  loop:
    - nut-server
    - nut-client
    - nut-driver@{{ ups_configuration__ups.name }}
