---
# Ansible
ansible_port: "1337"
ansible_become_pass: "{{ lookup('community.general.bitwarden', 'Proxmox VE david', field='password')[0] }}"

# System maintenance
apt_upgrade__cleanup:
  autoclean: true
  autoremove: true

# System configuration
linux__packages:
  - vim
  - tmux
  - htop

chrony_configuration__time:
  ntp_server: 192.168.178.3

remote_user_configuration__prompt:
  enabled: true
  color_code: 33

remote_user_configuration__tmux:
  enabled: true
  color: yellow
