---
# Ansible
ansible_port: "1337"

# System maintenance
apt_upgrade__cleanup:
  autoclean: true
  autoremove: true

# System configuration
linux__packages:
  - vim
  - tmux
  - htop

chrony__time:
  ntp_server: 192.168.178.3

remote_user__prompt:
  enabled: true
  color_code: 33

remote_user__tmux:
  enabled: true
  color: yellow

unattended_upgrades__report:
  mail:
    user: root # send to default alias for root
    sender: infra@dgries.de
  level: on-change
  verbose: false
  debug: false

postfix__relay:
  fqdn: smtp.mailbox.org
  port: 465

postfix__sender:
  username: mail@dgries.de
  mail: infra@dgries.de
  name: "{{ ansible_hostname }}"
  local_user: root
  canonical_file: /etc/postfix/sender_canonical
  alias_file: /etc/aliases
  header_checks_file: /etc/postfix/smtp_header_checks

postfix__smtp:
  credentials:
    username: "{{ lookup('community.general.bitwarden', 'Infrastructure Mail', field='username')[0] }}"
    password: "{{ lookup('community.general.bitwarden', 'Infrastructure Mail', field='password')[0] }}"
    file: /etc/postfix/smtp_credentials
    options: noanonymous
  tls:
    enabled: true
    enforced: true
    wrappermode_enabled: true
    security_level: encrypt
    ca_file: /etc/ssl/certs/ca-certificates.crt
