---
# Subscription key
proxmox__system:
  subscription_key: "{{ lookup('community.general.bitwarden', 'Proxmox VE Subscription', field='Subscription Key 1 CPU')[0] }}"

# System maintenance
apt_upgrade__update:
  type: dist
  refresh_cache: true
  force_apt_get: true

# System configuration
remote_user_configuration__admin:
  user: david
  create: true
  update_password: always
  password: "{{ lookup('community.general.bitwarden', 'Proxmox VE david', field='password')[0] }}"
  groups:
    - sudo
    - users

remote_user_configuration__ssh:
  sshport: "1337"
  sshkey: "{{ lookup('community.general.bitwarden', 'Proxmox VE david', field='SSH Public Key')[0] }}\n"
  enable_pubkey_auth: true
  enable_password_auth: false
  enable_x_forward: false
  enable_agent_auth: true
  authorized_keys_dir: /etc/ssh/sudo_authorized_keys

zed_configuration__notify:
  verbose: true
  zfs_data_event: true
  interval: 3600

unattended_upgrades_configuration__packages:
  origins:
    - origin: Debian
      codename: ${distro_codename}
      label: Debian
    - origin: Debian
      codename: ${distro_codename}
      label: Debian-Security
    - origin: Debian
      codename: ${distro_codename}-security
      label: Debian-Security
    - origin: Debian
      codename: ${distro_codename}-updates
      label: false
    - origin: Proxmox
      codename: ${distro_codename}
      label: Proxmox Ceph Enterprise Debian Repository
    - origin: Proxmox
      codename: ${distro_codename}
      label: Proxmox VE Enterprise Debian Repository
  blacklist: []

# PVE users and groups
pve_user_configuration__user:
  create: true
  name: admin
  password: "{{ lookup('community.general.bitwarden', 'Proxmox VE david', field='password')[0] }}"
  realm: pam
  groups:
    - vmadmin
  expire: 0
  firstname: David
  lastname: Gries
  comment: VM administration
  mail: infra@dgries.de

# UPS configuration
ups_configuration__user:
  username: upsmon
  password: "{{ lookup('community.general.bitwarden', 'Proxmox VE system', field='UPS Password')[0] }}"

# First setup configuration
linux__init:
  ansible_ssh_pass: "{{ lookup('community.general.bitwarden', 'Proxmox VE root', field='password')[0] }}"
  ansible_port: "22"
