---
# Host-specific subscription key
pve:
  subscription_key: "{{ lookup('community.general.bitwarden', 'Proxmox VE Subscription', field='Subscription Key 1 CPU')[0] }}"

# Host-specific UPS configuration
ups_configuration__user:
  username: upsmon
  password: "{{ lookup('community.general.bitwarden', 'Proxmox VE system', field='UPS Password') }}"

ups_configuration__nut:
  mode: standalone

ups_configuration__ups:
  maxretry: 3
  name: Eaton3S
  driver: usbhid-ups
  port: auto
