---
# Subscription key
proxmox__system:
  subscription_key: "{{ lookup('community.general.bitwarden', 'Proxmox VE Subscription', field='Subscription Key 1 CPU')[0] }}"

# System maintenance
apt_upgrade__update:
  type: dist
  refresh_cache: true
  force_apt_get: true

# System configuration
zed__notify:
  verbose: true
  zfs_data_event: true
  interval: 3600

unattended_upgrades__packages:
  origins:
    - origin: Debian
      codename: ${distro_codename}
      label: Debian
    - origin: Debian
      codename: ${distro_codename}
      label: Debian-Security
    - origin: Debian
      codename: ${distro_codename}-security
      label: Debian-Security
    - origin: Debian
      codename: ${distro_codename}-updates
      label: false
    - origin: Proxmox
      codename: ${distro_codename}
      label: Proxmox Ceph Enterprise Debian Repository
    - origin: Proxmox
      codename: ${distro_codename}
      label: Proxmox VE Enterprise Debian Repository
  blacklist: []
