---
# ================================================================================== #
# Author:  David Gries <mail@dgries.de>                                              #
# Project: homelab.ansible                                                           #
# License: MIT                                                                       #
# Purpose: initialize / update homelab site and declare configuration                #
# ================================================================================== #

- name: Configure Proxmox (initial install)
  ansible.builtin.import_playbook: playbooks/proxmox/plays/init.yaml
  tags:
    - init
    - init.proxmox
    - never

- name: Upgrade System
  ansible.builtin.import_playbook: playbooks/maintenance/plays/system_upgrade.yaml
  tags:
    - update
    - upgrade
    - never

- name: Configure Proxmox
  ansible.builtin.import_playbook: playbooks/proxmox/plays/proxmox.yaml
  tags:
    - proxmox
    - init
    - init.proxmox
