---
zed_configuration__mail:
  recipient: root
  program: mail
  options: -s '@SUBJECT@' @ADDRESS@

zed_configuration__notify:
  verbose: false
  zfs_data_event: true
  interval: 3600

zed_configuration__enclosure:
  use_leds: true

zed_configuration__scrub:
  after_resilver: false

zed_configuration__syslog:
  use_guids: false
  subclass_include:
    enabled: false
    content: checksum|scrub_*|vdev.*
  subclass_exclude:
    enabled: true
    content: history_event
