---
- name: Reload Chrony sources
  ansible.builtin.command:
    cmd: chronyc reload sources
  become: true
  changed_when: true
  listen:
    - Reload sources

- name: Restart Chrony after initialization
  ansible.builtin.service:
    name: chrony
    state: restarted
  become: true
  listen:
    - Restart Chrony
