---
internal:
  children:
    pihole:
    truenas:
    proxmox:

linux:
  children:
    pihole:
    truenas:
    proxmox:

hardware:
  children:
    proxmox:
    pihole:

proxmox:
  hosts:
    pve.host.dgries.internal:

truenas:
  hosts:
    tns.host.dgries.internal:

pihole:
  hosts:
    pi.host.dgries.internal:
