---
internal:
  children:
    pihole:
    truenas:
    proxmox:

linux:
  children:
    pihole:
    truenas:
    proxmox:
    ctr:

hardware:
  children:
    proxmox:
    pihole:
    truenas:

proxmox:
  hosts:
    pve.host.dgries.internal:

truenas:
  hosts:
    tns.host.dgries.internal:

ctr:
  hosts:
    ctr.host.dgries.internal:
    # ansible_host: 192.168.178.93

pihole:
  hosts:
    pi.host.dgries.internal:
