---
- name: Restart Jail
  ansible.builtin.command: "{{ jailmaker_bin.dest }} restart {{ jailmaker__jail.name }}"
  listen:
    - Restart Jail
  changed_when: true
  become: true

- name: Remove temporary config file
  ansible.builtin.file:
    path: "{{ jailmaker_tmp_config.dest }}"
    state: absent
  listen:
    - Remove temporary config
  become: true
