---
- name: Restart NUT services after configuration
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  become: true
  listen:
    - Restart NUT
  loop:
    - nut-server
    - nut-client
    - nut-driver@{{ ups__ups.name }}
