---
- name: Gather current user
  ansible.builtin.set_fact:
    current_user: "{{ lookup('env', 'USER') }}"

- name: Ensure sudo is installed
  ansible.builtin.package:
    name: sudo
  when: current_user == 'root'

- name: Ensure admin user is present
  ansible.builtin.user:
    name: "{{ remote_user_configuration_admin.user }}"
    groups:
      - sudo
      - users
    password: "{{ remote_user_configuration_admin.password | password_hash('sha512') }}"
    update_password: "{{ remote_user_configuration_admin.update_password }}"
  when: (current_user != remote_user_configuration_admin.user) and (remote_user_configuration_admin.create | bool)

- name: Adjust prompt
  ansible.builtin.template:
    src: ../templates/bashrc.j2 # noqa no-relative-paths
    dest: /home/{{ remote_user_configuration_admin.user }}/.bashrc
    owner: "{{ remote_user_configuration_admin.user }}"
    group: "{{ remote_user_configuration_admin.user }}"
    mode: "0644"
  when: remote_user_configuration_prompt.enabled | bool

- name: Configure SSH
  ansible.builtin.template:
    src: sshd_config.conf.j2
    dest: /etc/ssh/sshd_config.d/user.conf
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Add SSH keys to home
  ansible.builtin.copy:
    content: "{{ remote_user_configuration_ssh.sshkey }}"
    dest: /home/{{ remote_user_configuration_admin.user }}/.ssh/authorized_keys
    mode: "0600"
    owner: "{{ remote_user_configuration_admin.user }}"
    group: "{{ remote_user_configuration_admin.user }}"
  when: remote_user_configuration_ssh.enable_pubkey_auth | bool

- name: Configure PAM agent auth
  when: (remote_user_configuration_ssh.enable_pubkey_auth | bool) and (remote_user_configuration_ssh.enable_agent_auth | bool)
  become: true
  block:

    - name: Install libpam-ssh-agent-auth
      ansible.builtin.package:
        name: libpam-ssh-agent-auth

    - name: Template PAM sudo config
      ansible.builtin.template:
        src: pam_sudo.j2
        dest: /etc/pam.d/sudo
        mode: "0600"
        owner: root
        group: root

    - name: Add SSH keys for PAM sudo
      ansible.builtin.copy:
        content: "{{ remote_user_configuration_ssh.sshkey }}"
        dest: /etc/ssh/sudo_authorized_keys
        mode: "0600"
        owner: root
        group: root
