---
- name: Update all packages
  ansible.builtin.apt:
    autoclean: "{{ apt_upgrade__cleanup.autoclean }}"
    autoremove: "{{ apt_upgrade__cleanup.autoremove }}"
    update_cache: "{{ apt_upgrade__update.refresh_cache }}"
    upgrade: "{{ apt_upgrade__update.type }}"
    force_apt_get: "{{ apt_upgrade__update.force_apt_get }}"

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot system
  ansible.builtin.reboot:
  when: >
    (reboot_required.stat.exists and apt_upgrade__reboot.if_required) or
    apt_upgrade__reboot.always
