---
# Initialize new Proxmox instance using root user (idempotent)

- name: Proxmox Virtual Environment
  hosts: proxmox
  remote_user: root
  become: false
  vars:
    ansible_port: "{{ linux__init.ansible_port }}"
    ansible_ssh_pass: "{{ linux__init.ansible_ssh_pass }}"

  tasks:

    - name: Add subscription key
      ansible.builtin.command: pvesubscription set {{ proxmox__system.subscription_key }}
      args:
        creates: /etc/subscription

    - name: Upgrade packages
      ansible.builtin.import_role:
        name: apt_upgrade

    - name: Configure SSH admin user
      ansible.builtin.import_role:
        name: remote_user

    - name: Create initialized file
      ansible.builtin.copy:
        content: |
          Initialized using Ansible on {{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}
        dest: /etc/.initialization_done
        mode: "0644"
        owner: root
        group: root
        force: false
