---
# Initialize new Proxmox instance using root user (idempotent)

- name: Proxmox Virtual Environment
  hosts: proxmox
  vars_files:
    - ../vars/init.yaml
  remote_user: root
  become: false

  tasks:

    - name: Set SSH port to 22 for initialization
      ansible.builtin.set_fact:
        ansible_port: "22"

    - name: Add subscription key
      ansible.builtin.command: pvesubscription set {{ pve.subscription_key }}
      args:
        creates: /etc/subscription

    - name: Update and install packages
      block:

        - name: Update packages
          ansible.builtin.apt:
            autoclean: true
            autoremove: true
            update_cache: true
            upgrade: dist

    - name: Configure system
      block:

        - name: Configure SSH admin user
          ansible.builtin.import_role:
            name: ../../../roles/ssh_configuration # noqa: role-name
          vars:
            role_admin:
              user: "{{ hosts_admin.user }}"
              password: "{{ hosts_admin.password }}"
              update_password: "{{ hosts_admin.update_password }}"
              create: "{{ hosts_admin.create }}"
              groups: "{{ hosts_admin.groups }}"
            role_ssh:
              sshkey: "{{ hosts_ssh.sshkey }}\n"
              sshport: "{{ hosts_ssh.sshport }}"
              enable_pubkey_auth: "{{ hosts_ssh.enable_pubkey_auth }}"
              enable_agent_auth: "{{ hosts_ssh.enable_agent_auth }}"
              enable_password_auth: "{{ hosts_ssh.enable_password_auth }}"
              enable_x_forward: "{{ hosts_ssh.enable_x_forward }}"
              authorized_keys_dir: "{{ hosts_ssh.authorized_keys_dir }}"
          notify:
            - restart_sshd

  handlers:

    - name: Restart sshd after initialization
      ansible.builtin.systemd_service:
        state: restarted
        name: sshd
      listen:
        - restart_sshd
