---
# Initialize new Proxmox instance using root user (idempotent)

- name: Proxmox Virtual Environment
  hosts: proxmox
  vars_files:
    - ../vars/init.yaml
  remote_user: root
  become: false
  vars:
    ansible_port: "{{ hosts_init.ansible_port }}"
    ansible_ssh_pass: "{{ hosts_init.ansible_ssh_pass }}"

  tasks:

    - name: Add subscription key
      ansible.builtin.command: pvesubscription set {{ pve.subscription_key }}
      args:
        creates: /etc/subscription

    - name: Update packages
      ansible.builtin.apt:
        autoclean: true
        autoremove: true
        update_cache: true
        upgrade: dist

    - name: Configure SSH admin user
      ansible.builtin.import_role:
        name: remote_user_configuration
      notify:
        - restart_sshd

  handlers:

    - name: Restart sshd after initialization
      ansible.builtin.systemd_service:
        state: restarted
        name: sshd
      listen:
        - restart_sshd
