---
- name: Proxmox Virtual Environment
  hosts: proxmox
  vars_files:
    - ../vars/main.yaml
  remote_user: "{{ remote_user_configuration__admin.user }}"

  tasks:

    - name: Ensure default packages are present
      ansible.builtin.apt:
        name: "{{ linux__packages }}"
        update_cache: true
      become: true

    - name: Configure SSH admin user
      ansible.builtin.import_role:
        name: remote_user_configuration

    - name: Configure Chrony
      ansible.builtin.import_role:
        name: chrony_configuration

