---
- name: Proxmox Virtual Environment
  hosts: proxmox
  remote_user: "{{ remote_user__admin.user }}"
  tasks:

    - name: Configure Linux system
      tags:
        - linux_system
      block:

        - name: Set kernel boot parameters
          ansible.builtin.copy:
            content: "{{ kernel_cmdline }}\n"
            dest: /etc/kernel/cmdline
            backup: true
            mode: "0644"
            owner: root
            group: root
          when: kernel_cmdline is defined and kernel_cmdline
          notify:
            - Reboot
            - Update boot
          become: true
          tags:
            - boot_configuration

        - name: Ensure default packages are present
          ansible.builtin.apt:
            name: "{{ linux__packages }}"
            update_cache: true
          become: true
          tags:
            - default_packages

        - name: Configure SSH admin user
          ansible.builtin.import_role:
            name: remote_user
          tags:
            - remote_user

        - name: Configure Chrony
          ansible.builtin.import_role:
            name: chrony
          tags:
            - chrony

        - name: Configure Postfix
          ansible.builtin.import_role:
            name: postfix
          tags:
            - postfix

        - name: Configure UPS
          ansible.builtin.import_role:
            name: ups
          tags:
            - ups

        - name: Configure ZFS event daemon
          ansible.builtin.import_role:
            name: zed
          tags:
            - zed

        # - name: Configure automatc updates
        #   ansible.builtin.import_role:
        #     name: unattended_upgrades
        #   tags:
        #     - update_configuration

    - name: Configure PVE
      tags:
        - pve_system
      block:

        - name: Configure PVE admin user
          ansible.builtin.import_role:
            name: pve_user
          tags:
            - pve_user

  handlers:

    - name: Update kernel boot parameters # noqa no-changed-when
      ansible.builtin.command:
        cmd: proxmox-boot-tool refresh
      become: true
      listen:
        - Update boot

    - name: Reboot system
      ansible.builtin.reboot:
      listen:
        - Reboot
      become: true
