---
- name: TrueNAS SCALE Jails
  hosts: truenas
  remote_user: "{{ remote_user__admin.user }}"
  tasks:

    - name: Setup container environment
      tags:
        - tn_ctr
      block:

        - name: Setup Jails
          ansible.builtin.include_role:
            name: jailmaker
          tags:
            - tn_jailmaker
          vars:
            jailmaker__jail:
              name: testjail
              dataset: speed
