---
- name: Create group
  when: pve_user_configuration__group.create | bool
  block:

    - name: Get list of available groups
      ansible.builtin.command:
        cmd: pveum group list --noborder --noheader --output-format json
      register: pve_groups
      changed_when: false
      become: true

    - name: "Create group if it doesn't exist yet: {{ pve_user_configuration__group.name }}"
      ansible.builtin.command:
        cmd: pveum group add "{{ pve_user_configuration__group.name }}" --comment "{{ pve_user_configuration__group.comment }}"
      when: not pve_groups.stdout | from_json | json_query('[*].groupid') is contains(pve_user_configuration__group.name)
      changed_when: true
      become: true
