name: ansible-lint

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: ansible lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: run ansible-lint
        uses: ansible/ansible-lint@492d840530aa2e2b3281165d2353134ad796b156 # v24.5.0
